/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menuUtama;

import java.awt.Color;
import java.sql.Connection;
import javax.swing.JLabel;
import javax.swing.JPanel;
import Karyawan.karyawan;
import Karyawan.penilaian;
import Karyawan.perangkingan;
import menuUtama.dashbor;

/**
 *
 * @author serud
 */
public class menuUtama extends javax.swing.JFrame {

//    private Connection conn = new koneksi().connect();
    //fotm
    dashbor de;
    karyawan kr;
    penilaian pn;
    perangkingan pr;
//    about at;
    //
    
    /**
     * Creates new form menuUtama
     */
    public menuUtama() {
        initComponents();
        panel_form();// void
    }
    public void panel_form(){
        //jpanel form namanya diubah menjadi variabel
        de = new dashbor();
        kr = new Karyawan.karyawan();
        pn = new penilaian();
        pr = new perangkingan();
//        at = new about();
//        //memnanggil jpanel form ke panelyang sudah diubah menjadi variabel
        panelbody.add(de);
        panelbody.add(kr);
        panelbody.add(pn);
        panelbody.add(pr);
//        panelbody.add(at);
//        // variabel jpanel form awalan saat membuka form menu
        de.setVisible(true);
        kr.setVisible(false);
        pn.setVisible(false);
        pr.setVisible(false);
//        at.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jspitem = new javax.swing.JScrollPane();
        panel_kiri = new javax.swing.JPanel();
        btndashbord = new javax.swing.JPanel();
        lbldashbord = new javax.swing.JLabel();
        lblicon_dashbore_abu = new javax.swing.JLabel();
        lblicon_dashbore_biru = new javax.swing.JLabel();
        pnldashbord = new javax.swing.JPanel();
        btnkaryawan = new javax.swing.JPanel();
        lblkaryawan = new javax.swing.JLabel();
        pnlkaryawan = new javax.swing.JPanel();
        lblicon_karyawan_abu = new javax.swing.JLabel();
        lblicon_karyawan_biru = new javax.swing.JLabel();
        btnrangking = new javax.swing.JPanel();
        pnlrangking = new javax.swing.JPanel();
        lblrangking = new javax.swing.JLabel();
        lblicon_rangking_abu = new javax.swing.JLabel();
        lblicon_rangking_biru = new javax.swing.JLabel();
        btnpenilaian = new javax.swing.JPanel();
        lblpenilaian = new javax.swing.JLabel();
        pnlpenilaian = new javax.swing.JPanel();
        lblicon_penilaian_abu = new javax.swing.JLabel();
        lblicon_penilaian_biru = new javax.swing.JLabel();
        lbl_xy1 = new javax.swing.JLabel();
        usernamee = new javax.swing.JLabel();
        btnabout = new javax.swing.JPanel();
        pnlabout = new javax.swing.JPanel();
        lblabout = new javax.swing.JLabel();
        lblicon_about_abu = new javax.swing.JLabel();
        lblicon_about_biru = new javax.swing.JLabel();
        btnlogout = new javax.swing.JPanel();
        pnllogout = new javax.swing.JPanel();
        lblicon_logout_abu = new javax.swing.JLabel();
        lbllogout = new javax.swing.JLabel();
        jspbody = new javax.swing.JScrollPane();
        panelbody = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 248, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(966, 800));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 966, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );

        jspitem.setBorder(null);
        jspitem.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jspitem.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        panel_kiri.setBackground(new java.awt.Color(255, 255, 255));
        panel_kiri.setMinimumSize(new java.awt.Dimension(195, 410));
        panel_kiri.setName(""); // NOI18N
        panel_kiri.setPreferredSize(new java.awt.Dimension(300, 3000));

        btndashbord.setBackground(new java.awt.Color(255, 255, 255));
        btndashbord.setPreferredSize(new java.awt.Dimension(118, 40));
        btndashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndashbordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndashbordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndashbordMouseExited(evt);
            }
        });

        lbldashbord.setBackground(new java.awt.Color(0, 0, 0));
        lbldashbord.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbldashbord.setForeground(new java.awt.Color(0, 194, 255));
        lbldashbord.setText("Dashbord");

        lblicon_dashbore_abu.setBackground(new java.awt.Color(0, 0, 0));
        lblicon_dashbore_abu.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblicon_dashbore_abu.setForeground(new java.awt.Color(153, 153, 153));

        lblicon_dashbore_biru.setBackground(new java.awt.Color(0, 0, 0));
        lblicon_dashbore_biru.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblicon_dashbore_biru.setForeground(new java.awt.Color(153, 153, 153));

        pnldashbord.setBackground(new java.awt.Color(0, 194, 255));
        pnldashbord.setPreferredSize(new java.awt.Dimension(6, 30));

        javax.swing.GroupLayout pnldashbordLayout = new javax.swing.GroupLayout(pnldashbord);
        pnldashbord.setLayout(pnldashbordLayout);
        pnldashbordLayout.setHorizontalGroup(
            pnldashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pnldashbordLayout.setVerticalGroup(
            pnldashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btndashbordLayout = new javax.swing.GroupLayout(btndashbord);
        btndashbord.setLayout(btndashbordLayout);
        btndashbordLayout.setHorizontalGroup(
            btndashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btndashbordLayout.createSequentialGroup()
                .addComponent(pnldashbord, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(btndashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblicon_dashbore_abu)
                    .addComponent(lblicon_dashbore_biru))
                .addGap(8, 8, 8)
                .addComponent(lbldashbord, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(963, Short.MAX_VALUE))
        );
        btndashbordLayout.setVerticalGroup(
            btndashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btndashbordLayout.createSequentialGroup()
                .addGroup(btndashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnldashbord, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btndashbordLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(btndashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblicon_dashbore_abu)
                            .addComponent(lblicon_dashbore_biru)
                            .addComponent(lbldashbord))))
                .addGap(51, 51, 51))
        );

        btnkaryawan.setBackground(new java.awt.Color(255, 255, 255));
        btnkaryawan.setPreferredSize(new java.awt.Dimension(118, 40));
        btnkaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkaryawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnkaryawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnkaryawanMouseExited(evt);
            }
        });
        btnkaryawan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblkaryawan.setBackground(new java.awt.Color(0, 0, 0));
        lblkaryawan.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblkaryawan.setForeground(new java.awt.Color(153, 153, 153));
        lblkaryawan.setText("Karyawan");
        btnkaryawan.add(lblkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        pnlkaryawan.setBackground(new java.awt.Color(0, 194, 255));
        pnlkaryawan.setOpaque(false);
        pnlkaryawan.setPreferredSize(new java.awt.Dimension(6, 30));

        javax.swing.GroupLayout pnlkaryawanLayout = new javax.swing.GroupLayout(pnlkaryawan);
        pnlkaryawan.setLayout(pnlkaryawanLayout);
        pnlkaryawanLayout.setHorizontalGroup(
            pnlkaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pnlkaryawanLayout.setVerticalGroup(
            pnlkaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btnkaryawan.add(pnlkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 40));

        lblicon_karyawan_abu.setBackground(new java.awt.Color(0, 0, 0));
        lblicon_karyawan_abu.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblicon_karyawan_abu.setForeground(new java.awt.Color(153, 153, 153));
        btnkaryawan.add(lblicon_karyawan_abu, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 10, -1, -1));

        lblicon_karyawan_biru.setBackground(new java.awt.Color(0, 0, 0));
        lblicon_karyawan_biru.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblicon_karyawan_biru.setForeground(new java.awt.Color(153, 153, 153));
        btnkaryawan.add(lblicon_karyawan_biru, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 10, -1, -1));

        btnrangking.setBackground(new java.awt.Color(255, 255, 255));
        btnrangking.setPreferredSize(new java.awt.Dimension(118, 40));
        btnrangking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrangkingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnrangkingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnrangkingMouseExited(evt);
            }
        });
        btnrangking.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlrangking.setBackground(new java.awt.Color(0, 194, 255));
        pnlrangking.setOpaque(false);
        pnlrangking.setPreferredSize(new java.awt.Dimension(6, 30));

        javax.swing.GroupLayout pnlrangkingLayout = new javax.swing.GroupLayout(pnlrangking);
        pnlrangking.setLayout(pnlrangkingLayout);
        pnlrangkingLayout.setHorizontalGroup(
            pnlrangkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pnlrangkingLayout.setVerticalGroup(
            pnlrangkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btnrangking.add(pnlrangking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 40));

        lblrangking.setBackground(new java.awt.Color(0, 0, 0));
        lblrangking.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblrangking.setForeground(new java.awt.Color(153, 153, 153));
        lblrangking.setText("Rangking");
        btnrangking.add(lblrangking, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        lblicon_rangking_abu.setBackground(new java.awt.Color(255, 0, 0));
        lblicon_rangking_abu.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblicon_rangking_abu.setForeground(new java.awt.Color(153, 153, 153));
        btnrangking.add(lblicon_rangking_abu, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 11, -1, -1));

        lblicon_rangking_biru.setBackground(new java.awt.Color(255, 0, 0));
        lblicon_rangking_biru.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblicon_rangking_biru.setForeground(new java.awt.Color(153, 153, 153));
        btnrangking.add(lblicon_rangking_biru, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 11, -1, -1));

        btnpenilaian.setBackground(new java.awt.Color(255, 255, 255));
        btnpenilaian.setPreferredSize(new java.awt.Dimension(118, 40));
        btnpenilaian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpenilaianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpenilaianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpenilaianMouseExited(evt);
            }
        });

        lblpenilaian.setBackground(new java.awt.Color(0, 0, 0));
        lblpenilaian.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblpenilaian.setForeground(new java.awt.Color(153, 153, 153));
        lblpenilaian.setText("Penilaian");

        pnlpenilaian.setBackground(new java.awt.Color(0, 194, 255));
        pnlpenilaian.setOpaque(false);
        pnlpenilaian.setPreferredSize(new java.awt.Dimension(6, 30));

        javax.swing.GroupLayout pnlpenilaianLayout = new javax.swing.GroupLayout(pnlpenilaian);
        pnlpenilaian.setLayout(pnlpenilaianLayout);
        pnlpenilaianLayout.setHorizontalGroup(
            pnlpenilaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pnlpenilaianLayout.setVerticalGroup(
            pnlpenilaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        lblicon_penilaian_abu.setBackground(new java.awt.Color(0, 0, 0));
        lblicon_penilaian_abu.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblicon_penilaian_abu.setForeground(new java.awt.Color(153, 153, 153));

        lblicon_penilaian_biru.setBackground(new java.awt.Color(0, 0, 0));
        lblicon_penilaian_biru.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblicon_penilaian_biru.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout btnpenilaianLayout = new javax.swing.GroupLayout(btnpenilaian);
        btnpenilaian.setLayout(btnpenilaianLayout);
        btnpenilaianLayout.setHorizontalGroup(
            btnpenilaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnpenilaianLayout.createSequentialGroup()
                .addComponent(pnlpenilaian, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(btnpenilaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblicon_penilaian_biru)
                    .addComponent(lblicon_penilaian_abu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblpenilaian)
                .addContainerGap())
        );
        btnpenilaianLayout.setVerticalGroup(
            btnpenilaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlpenilaian, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(btnpenilaianLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(btnpenilaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblicon_penilaian_biru)
                    .addComponent(lblicon_penilaian_abu)))
            .addComponent(lblpenilaian)
        );

        lbl_xy1.setBackground(new java.awt.Color(0, 0, 0));
        lbl_xy1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lbl_xy1.setForeground(new java.awt.Color(0, 194, 255));
        lbl_xy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/images.png"))); // NOI18N
        lbl_xy1.setLabelFor(lbl_xy1);
        lbl_xy1.setText("SPK");
        lbl_xy1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        lbl_xy1.setPreferredSize(new java.awt.Dimension(100, 100));

        usernamee.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        usernamee.setForeground(new java.awt.Color(102, 102, 102));
        usernamee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernamee.setText("USERNAME");

        btnabout.setBackground(new java.awt.Color(255, 255, 255));
        btnabout.setPreferredSize(new java.awt.Dimension(118, 40));
        btnabout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnaboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnaboutMouseExited(evt);
            }
        });

        pnlabout.setBackground(new java.awt.Color(0, 194, 255));
        pnlabout.setOpaque(false);
        pnlabout.setPreferredSize(new java.awt.Dimension(6, 30));

        javax.swing.GroupLayout pnlaboutLayout = new javax.swing.GroupLayout(pnlabout);
        pnlabout.setLayout(pnlaboutLayout);
        pnlaboutLayout.setHorizontalGroup(
            pnlaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pnlaboutLayout.setVerticalGroup(
            pnlaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        lblabout.setBackground(new java.awt.Color(0, 0, 0));
        lblabout.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblabout.setForeground(new java.awt.Color(153, 153, 153));
        lblabout.setText("About");

        lblicon_about_abu.setBackground(new java.awt.Color(255, 0, 0));
        lblicon_about_abu.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblicon_about_abu.setForeground(new java.awt.Color(153, 153, 153));

        lblicon_about_biru.setBackground(new java.awt.Color(255, 0, 0));
        lblicon_about_biru.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblicon_about_biru.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout btnaboutLayout = new javax.swing.GroupLayout(btnabout);
        btnabout.setLayout(btnaboutLayout);
        btnaboutLayout.setHorizontalGroup(
            btnaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnaboutLayout.createSequentialGroup()
                .addComponent(pnlabout, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(btnaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblicon_about_abu)
                    .addComponent(lblicon_about_biru))
                .addGap(18, 18, 18)
                .addComponent(lblabout)
                .addContainerGap())
        );
        btnaboutLayout.setVerticalGroup(
            btnaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnaboutLayout.createSequentialGroup()
                .addGroup(btnaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlabout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btnaboutLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(btnaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblicon_about_abu)
                            .addComponent(lblicon_about_biru)))
                    .addComponent(lblabout, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnlogout.setBackground(new java.awt.Color(255, 255, 255));
        btnlogout.setPreferredSize(new java.awt.Dimension(118, 40));
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlogoutMouseExited(evt);
            }
        });

        pnllogout.setBackground(new java.awt.Color(0, 194, 255));
        pnllogout.setOpaque(false);
        pnllogout.setPreferredSize(new java.awt.Dimension(6, 30));

        javax.swing.GroupLayout pnllogoutLayout = new javax.swing.GroupLayout(pnllogout);
        pnllogout.setLayout(pnllogoutLayout);
        pnllogoutLayout.setHorizontalGroup(
            pnllogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pnllogoutLayout.setVerticalGroup(
            pnllogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        lblicon_logout_abu.setBackground(new java.awt.Color(255, 0, 0));
        lblicon_logout_abu.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblicon_logout_abu.setForeground(new java.awt.Color(153, 153, 153));

        lbllogout.setBackground(new java.awt.Color(0, 0, 0));
        lbllogout.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbllogout.setForeground(new java.awt.Color(153, 153, 153));
        lbllogout.setText("Logout");

        javax.swing.GroupLayout btnlogoutLayout = new javax.swing.GroupLayout(btnlogout);
        btnlogout.setLayout(btnlogoutLayout);
        btnlogoutLayout.setHorizontalGroup(
            btnlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnlogoutLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(pnllogout, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(btnlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnlogoutLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(lblicon_logout_abu))
                    .addGroup(btnlogoutLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lbllogout)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnlogoutLayout.setVerticalGroup(
            btnlogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnllogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(btnlogoutLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbllogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblicon_logout_abu))
        );

        javax.swing.GroupLayout panel_kiriLayout = new javax.swing.GroupLayout(panel_kiri);
        panel_kiri.setLayout(panel_kiriLayout);
        panel_kiriLayout.setHorizontalGroup(
            panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnpenilaian, javax.swing.GroupLayout.DEFAULT_SIZE, 1149, Short.MAX_VALUE)
            .addGroup(panel_kiriLayout.createSequentialGroup()
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnabout, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE))
            .addGroup(panel_kiriLayout.createSequentialGroup()
                .addGroup(panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnrangking, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnkaryawan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btndashbord, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1149, Short.MAX_VALUE))
                    .addComponent(usernamee, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_xy1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_kiriLayout.setVerticalGroup(
            panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kiriLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lbl_xy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernamee)
                .addGap(49, 49, 49)
                .addComponent(btndashbord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnkaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnpenilaian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnrangking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_kiriLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnabout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_kiriLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2553, 2553, 2553))
        );

        jspitem.setViewportView(panel_kiri);

        jspbody.setBorder(null);
        jspbody.setMinimumSize(new java.awt.Dimension(1300, 700));

        panelbody.setBackground(new java.awt.Color(204, 0, 204));
        panelbody.setMinimumSize(new java.awt.Dimension(1300, 900));
        panelbody.setLayout(new javax.swing.BoxLayout(panelbody, javax.swing.BoxLayout.LINE_AXIS));
        jspbody.setViewportView(panelbody);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jspitem, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspbody, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(395, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(124, 124, 124)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspitem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jspbody, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashbordMouseClicked
        //set atau reset warna label item
        setlabelColor(lbldashbord);
        resetlabelColor(lblkaryawan);
        resetlabelColor(lblpenilaian);
        resetlabelColor(lblrangking);
        resetlabelColor(lblabout);
        //
        // set atau reswt warna panel kiri item
        setpanelColor(pnldashbord);
        resetpanelColor(pnlkaryawan);
        resetpanelColor(pnlpenilaian);
        resetpanelColor(pnlrangking);
        resetpanelColor(pnlabout);
        //
        //tampil awal sebelum dirun pada panel kiri item
        pnldashbord.setOpaque(true);
        pnlkaryawan.setOpaque(false);
        pnlpenilaian.setOpaque(false);
        pnlrangking.setOpaque(false);
        pnlabout.setOpaque(false);
        //
        //menampilkan atau tidak icon pada panel item
        lblicon_dashbore_abu.setVisible(false);
        lblicon_dashbore_biru.setVisible(true);
        lblicon_karyawan_abu.setVisible(true);
        lblicon_karyawan_biru.setVisible(false);
        lblicon_rangking_abu.setVisible(true);
        lblicon_rangking_biru.setVisible(false);
        lblicon_penilaian_abu.setVisible(true);
        lblicon_penilaian_biru.setVisible(false);
        lblicon_about_abu.setVisible(true);
        lblicon_about_biru.setVisible(false);
        //
        //memilih form sesuai yang dipilih
        de.setVisible(true);
        kr.setVisible(false);
        pn.setVisible(false);
        pr.setVisible(false);
//        at.setVisible(false);
        // btn input
    }//GEN-LAST:event_btndashbordMouseClicked

    private void btndashbordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashbordMouseEntered
        setColorEntered(btndashbord);
    }//GEN-LAST:event_btndashbordMouseEntered

    private void btndashbordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashbordMouseExited
        resetColorExited(btndashbord);
    }//GEN-LAST:event_btndashbordMouseExited

    private void btnkaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkaryawanMouseClicked
        //set atau reset warna label item
        resetlabelColor(lbldashbord);
        setlabelColor(lblkaryawan);
        resetlabelColor(lblpenilaian);
        resetlabelColor(lblrangking);
        resetlabelColor(lblabout);
        //
        // set atau reswt warna panel kiri item
        resetpanelColor(pnldashbord);
        setpanelColor(pnlkaryawan);
        resetpanelColor(pnlpenilaian);
        resetpanelColor(pnlrangking);
        resetpanelColor(pnlabout);
        //
        //tampil awal sebelum dirun pada panel kiri item
        pnldashbord.setOpaque(false);
        pnlkaryawan.setOpaque(true);
        pnlpenilaian.setOpaque(false);
        pnlrangking.setOpaque(false);
        pnlabout.setOpaque(false);
        //
        //menampilkan atau tidak icon pada panel item
        lblicon_dashbore_abu.setVisible(true);
        lblicon_dashbore_biru.setVisible(false);
        lblicon_karyawan_abu.setVisible(false);
        lblicon_karyawan_biru.setVisible(true);
        lblicon_rangking_abu.setVisible(true);
        lblicon_rangking_biru.setVisible(false);
        lblicon_penilaian_abu.setVisible(true);
        lblicon_penilaian_biru.setVisible(false);
        lblicon_about_abu.setVisible(true);
        lblicon_about_biru.setVisible(false);
        //
        //memilih form sesuai yang dipilih
        de.setVisible(false);
        kr.setVisible(true);
        pn.setVisible(false);
        pr.setVisible(false);
//        at.setVisible(false);
        // btn input
        btnkaryawan.setVisible(true);
        btnpenilaian.setVisible(true);
        btnabout.setVisible(true);
    }//GEN-LAST:event_btnkaryawanMouseClicked

    private void btnkaryawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkaryawanMouseEntered
        setColorEntered(btnkaryawan);
    }//GEN-LAST:event_btnkaryawanMouseEntered

    private void btnkaryawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkaryawanMouseExited
        resetColorExited(btnkaryawan);
    }//GEN-LAST:event_btnkaryawanMouseExited

    private void btnrangkingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrangkingMouseClicked
        //set atau reset warna label item
        resetlabelColor(lbldashbord);
        resetlabelColor(lblkaryawan);
        resetlabelColor(lblpenilaian);
        setlabelColor(lblrangking);
        resetlabelColor(lblabout);
        resetlabelColor(lblabout);
        //
        // set atau reswt warna panel kiri item
        resetpanelColor(pnldashbord);
        resetpanelColor(pnlkaryawan);
        resetpanelColor(pnlpenilaian);
        setpanelColor(pnlrangking);
        resetpanelColor(pnlabout);
        //
        //tampil awal sebelum dirun pada panel kiri item
        pnldashbord.setOpaque(false);
        pnlkaryawan.setOpaque(false);
        pnlpenilaian.setOpaque(false);
        pnlrangking.setOpaque(true);
        pnlabout.setOpaque(false);
        //
        //menampilkan atau tidak icon pada panel item
        lblicon_dashbore_abu.setVisible(true);
        lblicon_dashbore_biru.setVisible(false);
        lblicon_karyawan_abu.setVisible(true);
        lblicon_karyawan_biru.setVisible(false);
        lblicon_rangking_abu.setVisible(false);
        lblicon_rangking_biru.setVisible(true);
        lblicon_penilaian_abu.setVisible(true);
        lblicon_penilaian_biru.setVisible(false);
        lblicon_about_abu.setVisible(true);
        lblicon_about_biru.setVisible(false);
        //
        //memilih form sesuai yang dipilih
        de.setVisible(false);
        kr.setVisible(false);
        pn.setVisible(false);
        pr.setVisible(true);
//        at.setVisible(false);

        //btn input
        btnkaryawan.setVisible(true);
        btnpenilaian.setVisible(true);
        btnabout.setVisible(true);
    }//GEN-LAST:event_btnrangkingMouseClicked

    private void btnrangkingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrangkingMouseEntered
        setColorEntered(btnrangking);
    }//GEN-LAST:event_btnrangkingMouseEntered

    private void btnrangkingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrangkingMouseExited
        resetColorExited(btnrangking);
    }//GEN-LAST:event_btnrangkingMouseExited

    private void btnpenilaianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpenilaianMouseClicked
        //set atau reset warna label item
        resetlabelColor(lbldashbord);
        resetlabelColor(lblkaryawan);
        setlabelColor(lblpenilaian);
        resetlabelColor(lblrangking);
        resetlabelColor(lblabout);
        //
        // set atau reswt warna panel kiri item
        resetpanelColor(pnldashbord);
        resetpanelColor(pnlkaryawan);
        setpanelColor(pnlpenilaian);
        resetpanelColor(pnlrangking);
        resetpanelColor(pnlabout);
        //
        //tampil awal sebelum dirun pada panel kiri item
        pnldashbord.setOpaque(false);
        pnlkaryawan.setOpaque(false);
        pnlpenilaian.setOpaque(true);
        pnlrangking.setOpaque(false);
        pnlabout.setOpaque(false);
        //
        //menampilkan atau tidak icon pada panel item
        lblicon_dashbore_abu.setVisible(true);
        lblicon_dashbore_biru.setVisible(false);
        lblicon_karyawan_abu.setVisible(true);
        lblicon_karyawan_biru.setVisible(false);
        lblicon_rangking_abu.setVisible(true);
        lblicon_rangking_biru.setVisible(false);
        lblicon_penilaian_abu.setVisible(false);
        lblicon_penilaian_biru.setVisible(true);
        lblicon_about_abu.setVisible(true);
        lblicon_about_biru.setVisible(false);
        //
        //memilih form sesuai yang dipilih
        de.setVisible(false);
        kr.setVisible(false);
        pn.setVisible(true);
        pr.setVisible(false);
//        at.setVisible(false);
        // btn input
        btnkaryawan.setVisible(true);
        btnpenilaian.setVisible(true);
        btnabout.setVisible(true);
    }//GEN-LAST:event_btnpenilaianMouseClicked

    private void btnpenilaianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpenilaianMouseEntered
        setColorEntered(btnpenilaian);
    }//GEN-LAST:event_btnpenilaianMouseEntered

    private void btnpenilaianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpenilaianMouseExited
        resetColorExited(btnpenilaian);
    }//GEN-LAST:event_btnpenilaianMouseExited
    
    private void btnaboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaboutMouseClicked
        //set atau reset warna label item
        resetlabelColor(lbldashbord);
        resetlabelColor(lblkaryawan);
        resetlabelColor(lblpenilaian);
        resetlabelColor(lblrangking);
        setlabelColor(lblabout);
        //
        // set atau reswt warna panel kiri item
        resetpanelColor(pnldashbord);
        resetpanelColor(pnlkaryawan);
        resetpanelColor(pnlpenilaian);
        resetpanelColor(pnlrangking);
        setpanelColor(pnlabout);
        //
        //tampil awal sebelum dirun pada panel kiri item
        pnldashbord.setOpaque(false);
        pnlkaryawan.setOpaque(false);
        pnlpenilaian.setOpaque(false);
        pnlrangking.setOpaque(false);
        pnlabout.setOpaque(true);
        //
        //menampilkan atau tidak icon pada panel item
        lblicon_dashbore_abu.setVisible(true);
        lblicon_dashbore_biru.setVisible(false);
        lblicon_karyawan_abu.setVisible(true);
        lblicon_karyawan_biru.setVisible(false);
        lblicon_rangking_abu.setVisible(true);
        lblicon_rangking_biru.setVisible(false);
        lblicon_penilaian_abu.setVisible(true);
        lblicon_penilaian_biru.setVisible(false);
        lblicon_about_abu.setVisible(false);
        lblicon_about_biru.setVisible(true);
        //
        //memilih form sesuai yang dipilih
        de.setVisible(false);
        kr.setVisible(false);
        pn.setVisible(false);
        pr.setVisible(false);
//        at.setVisible(true);
        // btn input
        btnkaryawan.setVisible(true);
        btnpenilaian.setVisible(true);
        btnpenilaian.setVisible(true);
    }//GEN-LAST:event_btnaboutMouseClicked

    private void btnaboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaboutMouseEntered
        setColorEntered(btnabout);
    }//GEN-LAST:event_btnaboutMouseEntered

    private void btnaboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaboutMouseExited
        resetColorExited(btnabout);
    }//GEN-LAST:event_btnaboutMouseExited

    private void btnlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseClicked
        this.setVisible(false);
//        Login lg = new Login();
//        lg.setVisible(true);
    }//GEN-LAST:event_btnlogoutMouseClicked

    private void btnlogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseEntered
        setColorEntered(btnlogout);
    }//GEN-LAST:event_btnlogoutMouseEntered

    private void btnlogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseExited
        resetColorExited(btnlogout);
    }//GEN-LAST:event_btnlogoutMouseExited

    //warna button even entered dan exited
    void setColorEntered(JPanel panel){
        panel.setBackground(new Color(222,244,251));
    }
    void resetColorExited(JPanel panel){
        panel.setBackground(new Color(255,255,255));
    }
    //
    //warna label
    void setlabelColor(JLabel label){
        label.setForeground(new Color(0,194,255));
    }
    
    void resetlabelColor(JLabel label){
        label.setForeground(new Color(153,153,153));
    }
    //
    //warna panel
    void setpanelColor(JPanel panel){
        panel.setForeground(new Color(0,194,255));
    }
    void resetpanelColor(JPanel panel){
        panel.setForeground(new Color(249,250,252));
    }
    //
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnabout;
    private javax.swing.JPanel btndashbord;
    private javax.swing.JPanel btnkaryawan;
    private javax.swing.JPanel btnlogout;
    private javax.swing.JPanel btnpenilaian;
    private javax.swing.JPanel btnrangking;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jspbody;
    private javax.swing.JScrollPane jspitem;
    private javax.swing.JLabel lbl_xy1;
    private javax.swing.JLabel lblabout;
    private javax.swing.JLabel lbldashbord;
    private javax.swing.JLabel lblicon_about_abu;
    private javax.swing.JLabel lblicon_about_biru;
    private javax.swing.JLabel lblicon_dashbore_abu;
    private javax.swing.JLabel lblicon_dashbore_biru;
    private javax.swing.JLabel lblicon_karyawan_abu;
    private javax.swing.JLabel lblicon_karyawan_biru;
    private javax.swing.JLabel lblicon_logout_abu;
    private javax.swing.JLabel lblicon_penilaian_abu;
    private javax.swing.JLabel lblicon_penilaian_biru;
    private javax.swing.JLabel lblicon_rangking_abu;
    private javax.swing.JLabel lblicon_rangking_biru;
    private javax.swing.JLabel lblkaryawan;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JLabel lblpenilaian;
    private javax.swing.JLabel lblrangking;
    private javax.swing.JPanel panel_kiri;
    private javax.swing.JPanel panelbody;
    private javax.swing.JPanel pnlabout;
    private javax.swing.JPanel pnldashbord;
    private javax.swing.JPanel pnlkaryawan;
    private javax.swing.JPanel pnllogout;
    private javax.swing.JPanel pnlpenilaian;
    private javax.swing.JPanel pnlrangking;
    public static volatile javax.swing.JLabel usernamee;
    // End of variables declaration//GEN-END:variables
}
